Cleaned up the messaging.

diff --git a/library/nvm_tool b/library/nvm_tool
--- a/library/nvm_tool
+++ b/library/nvm_tool
@@ -7,54 +7,91 @@
 args=$(cat $1 | sed 's/,//g')
 eval $args
 
-# echo "A = $value"
-# echo "B = $name"
+successResponse() {
+  message=$1
+  changed=$2
+
+  echo "{ \"result\" : \"${message}\", \"changed\" : ${changed} }"
+}
+
+failureResponse() {
+  message=$1
+
+  echo "{ \"failed\" : true, \"msg\" : \"${message}\" }"
+
+  return 1
+}
+
+response() {
+  error_code=$1
+  success_message=$2
+  failure_message=$3
+  changed=$4
+
+  if [ $error_code == 0 ]
+  then
+    successResponse "$2" $4
+  else
+    failureResponse "$3"
+  fi
+
+  return ${error_code}
+}
+
+installNVM() {
+  if [ -d ~/.nvm ]
+  then
+    successResponse "NVM already installed" false
+    return 0
+  else
+    curl -s -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.4/install.sh | bash > /dev/null 2>&1
+    response $? "Installed NVM", "Error installing NVM" true
+    return $?
+  fi
+}
+
+installNode() {
+  node_version=$1
+
+  if [ ! -d ~/.nvm ]
+  then
+    failureResponse "NVM is not installed"
+    return 1
+  fi
+
+  if [ -z "$node_version" ]
+  then
+    failureResponse "No node version specified"
+    return 1
+  fi
+
+  source ~/.nvm/nvm.sh > /dev/null 2>&1 && nvm exec ${node_version} node -e 'console.log("test")' > /dev/null 2>&1
+  if [ $? == 0 ]
+  then
+    successResponse "Node ${node_version} already installed", false
+    return 0
+  fi
+
+  source ~/.nvm/nvm.sh > /dev/null 2>&1 && nvm install ${node_version} > /tmp/install_node.log 2>&1
+  response \
+    $? \
+    "Node ${node_version} successfully installed" \
+    "Error installing node ${node_version}" \
+    true
+
+  return $?
+}
+
 case "$action" in
   install)
-    if [ -d ~/.nvm ]
-    then
-      echo "{ \"result\" : \"NVM already installed\", \"changed\" : false }"
-      exit 0
-    else
-      curl -s -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.4/install.sh | bash > /dev/null 2>&1
-      if [ $? == 0 ]
-      then
-        echo "{ \"result\" : \"Installed NVM\", \"changed\" : true }"
-      else
-        echo "{ \"failed\" :true, \"msg\" : \"Error installing NVM\" }"
-        exit 1
-      fi
-    fi
+    installNVM
     ;;
   setup)
-    if [ -z "$node_version" ]
-    then
-      echo "{ \"failed\" : true, \"msg\" : \"No node version specified\" }"
-      exit 1
-    else
-      source ~/.nvm/nvm.sh > /dev/null 2>&1 && nvm exec ${node_version} node -e 'console.log("test")' > /dev/null 2>&1
-      if [ $? == 0 ]
-      then
-        echo "{ \"result\" : \"Node ${node_version} already installed\", \"changed\" : false }"
-        exit 0
-      else
-        source ~/.nvm/nvm.sh > /dev/null 2>&1 && nvm install ${node_version} > /tmp/install_node.log 2>&1
-        if [ $? == 0 ]
-        then
-          echo "{ \"result\" : \"Node ${node_version} successfully installed\", \"changed\" : true }"
-          exit 0
-        else
-          echo "{ \"failed\" : true, \"msg\" : \"Error installing node ${node_version}\" }"
-          exit 1
-        fi
-      fi
-    fi
-    ;;
-  list)
-    echo "{ \"result\" : \"Going to list nodes\" }"
+    installNode $node_version
     ;;
   *)
-    echo "{ \"failed\" : true, \"msg\" : \"Invalid action specified\" }"
-    exit 1
+    failureResponse "Invalid action specified"
     ;;
 esac
+
+exit $?
